version: "3.7"

services:
  database:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbroot
      MYSQL_DATABASE: frame_example
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./init:/docker-entrypoint-initdb.

