# Generated by Django 3.2.9 on 2022-06-06 15:33

from django.db import migrations, models
import django.db.models.deletion
from django_frames.extensions import FramedModel


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20220606_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=(models.Model, FramedModel),
        ),
        migrations.AddField(
            model_name='club',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.college'),
        ),
    ]
